# Generated by Django 3.0.8 on 2020-10-02 08:55

import bluebottle.files.validators
import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0007_auto_20200903_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='background_image',
            field=bluebottle.utils.fields.ImageField(blank=True, max_length=255, null=True, upload_to='banner_slides/', verbose_name='Background image'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, max_length=255, null=True, upload_to='banner_slides/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], db_index=True, default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='style',
            field=models.CharField(blank=True, default='default', help_text='Styling class name', max_length=40, verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='video',
            field=models.FileField(blank=True, help_text='This video will autoplay at the background. Allowed types are mp4, ogg, 3gp, avi, mov and webm. File should be smaller then 10MB.', max_length=255, null=True, upload_to='banner_slides/', validators=[bluebottle.files.validators.validate_video_file_size, bluebottle.utils.validators.FileMimetypeValidator(['video/ogg', 'video/mp4', 'video/webm', 'video/3gpp', 'video/x-msvideo', 'video/quicktime'], None, 'invalid_mimetype')], verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=100, verbose_name='Video url'),
        ),
    ]
