# Generated by Django 3.0.8 on 2020-10-02 08:55

import bluebottle.utils.fields
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0054_auto_20200610_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='legacypayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='paymentprovider',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='payoutaccount',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default_currency='EUR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default_currency='EUR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payout_amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default_currency='EUR', max_digits=12),
        ),
        migrations.AlterField(
            model_name='funding',
            name='target_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default_currency='EUR', max_digits=12, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='paymentcurrency',
            name='code',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='payoutaccount',
            name='status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=bluebottle.utils.fields.MoneyField(currency_choices=[('EUR', 'Euro')], decimal_places=2, default_currency='EUR', max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3),
        ),
    ]
