# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallposts', '0020_auto_20191017_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediawallpost',
            options={'base_manager_name': 'objects', 'permissions': (('api_read_own_textwallpost', 'Can view own text wallposts through the API'), ('api_add_own_textwallpost', 'Can add own text wallposts through the API'), ('api_change_own_textwallpost', 'Can change text wallposts through the API'), ('api_delete_own_textwallpost', 'Can delete own text wallposts through the API'), ('api_read_textwallpost', 'Can view text wallposts through the API'), ('api_add_textwallpost', 'Can add text wallposts through the API'), ('api_change_textwallpost', 'Can change text wallposts through the API'), ('api_delete_textwallpost', 'Can delete text wallposts through the API'), ('api_read_mediawallpost', 'Can view media wallposts through the API'), ('api_add_mediawallpost', 'Can add media wallposts through the API'), ('api_change_mediawallpost', 'Can change media wallposts through the API'), ('api_delete_mediawallpost', 'Can delete media wallposts through the API'), ('api_read_own_mediawallpost', 'Can view own media wallposts through the API'), ('api_add_own_mediawallpost', 'Can add own media wallposts through the API'), ('api_change_own_mediawallpost', 'Can change own media wallposts through the API'), ('api_delete_own_mediawallpost', 'Can delete own media wallposts through the API'), ('api_read_mediawallpostphoto', 'Can view media wallpost photos through the API'), ('api_add_mediawallpostphoto', 'Can add media wallpost photos through the API'), ('api_change_mediawallpostphoto', 'Can change media wallpost photos through the API'), ('api_delete_mediawallpostphoto', 'Can delete media wallpost photos through the API'), ('api_read_own_mediawallpostphoto', 'Can view own media wallpost photos through the API'), ('api_add_own_mediawallpostphoto', 'Can add own media wallpost photos through the API'), ('api_change_own_mediawallpostphoto', 'Can change own media wallpost photos through the API'), ('api_delete_own_mediawallpostphoto', 'Can delete own media wallpost photos through the API'))},
        ),
        migrations.AlterModelOptions(
            name='systemwallpost',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='textwallpost',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='mediawallpost',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='systemwallpost',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='textwallpost',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='mediawallpost',
            name='text',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mediawallpost',
            name='title',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='mediawallpost',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mediawallpostphoto',
            name='photo',
            field=models.ImageField(upload_to='mediawallpostphotos'),
        ),
        migrations.AlterField(
            model_name='wallpost',
            name='pinned',
            field=models.BooleanField(default=False, help_text='Pinned posts are shown first. New posts by the initiator will unpin older posts.'),
        ),
    ]
