# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_vitepay', '0002_delete_vitepaypayment'),
        ('payments_voucher', '0002_auto_20201002_1055'),
        ('payments_beyonic', '0002_delete_beyonicpayment'),
        ('payments_logger', '0002_delete_paymentlogentry'),
        ('payments_stripe', '0004_delete_stripepayment'),
        ('payments_pledge', '0002_delete_pledgestandardpayment'),
        ('payments', '0007_auto_20201002_1055'),
        ('payments_telesom', '0002_delete_telesompayment'),
        ('payments_docdata', '0005_auto_20201002_1055'),
        ('payments_lipisha', '0003_auto_20201002_1055'),
        ('payments_interswitch', '0004_auto_20201002_1055'),
        ('payments_external', '0002_delete_externalpayment'),
        ('payments_flutterwave', '0009_auto_20201002_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
