# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200124_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='adapter',
            field=models.CharField(default='email', max_length=30),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='message',
            field=models.CharField(choices=[('bluebottle.members.messages.AccountActivationMessage', 'Member activated')], max_length=500, unique=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='messagetemplatetranslation',
            name='body_txt',
            field=models.TextField(blank=True, verbose_name='Body (text)'),
        ),
        migrations.AlterField(
            model_name='messagetemplatetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notifications.MessageTemplate'),
        ),
        migrations.AlterField(
            model_name='notificationplatformsettings',
            name='match_options',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('theme', 'Theme'), ('skill', 'Skill'), ('location', 'Location')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationplatformsettings',
            name='share_options',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('twitter', 'Twitter'), ('facebook', 'Facebook'), ('facebookAtWork', 'Facebook at Work'), ('linkedin', 'LinkedIn'), ('whatsapp', 'Whatsapp'), ('yammer', 'Yammer'), ('email', 'Email')], max_length=100),
        ),
    ]
