dist: xenial
sudo: false
language: python
addons:
  postgresql: "10"
  apt:
    packages:
      - libxmlsec1
      - libxmlsec1-dev
      - libgdal-dev
      - swig
      - openjdk-8-jdk-headless
      - postgresql-client-10
cache: pip
  - "$HOME/.cache/pip/"
  - "$HOME/virtualenv/python2.7.15/lib/python2.7/site-packages"
python:
  - 3.7
services:
  - elasticsearch
  - postgresql
env:
  global:
  - DJANGO_SETTINGS_MODULE='bluebottle.settings.testing'
matrix:
  - env: DJANGO_VERSION=1.11
  - env: DJANGO_VERSION=3.1
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.6.0.deb && sudo service elasticsearch restart
  - createdb test_bluebottle_test
  - psql test_bluebottle_test < testdata.sql
  - psql -c "CREATE USER testuser WITH PASSWORD 'password'"
  - psql -c "ALTER ROLE testuser SUPERUSER"
install:
  - pip install --upgrade pip
  - pip install --upgrade wheel setuptools mercurial
  - pip install --upgrade 'git+https://github.com/jayvdb/compat-patcher-core@i1'
  - pip install --upgrade django-compat-patcher
  - pip install "Django~=$DJANGO_VERSION.*"
  - pip install -e .[test] --trusted-host github.com
script:
  - mkdir tenants
  - python -m coverage run --parallel-mode --source=bluebottle manage.py test --keepdb
