# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_flutterwave', '0008_auto_20200106_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flutterwavepayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='flutterwavebankaccount',
            name='bank_code',
            field=models.CharField(blank=True, choices=[('', 'Select bank'), ('044', 'Access Bank'), ('063', 'Access Bank PLC (Diamond)'), ('023', 'Citi Bank'), ('050', 'EcoBank PLC'), ('070', 'Fidelity Bank'), ('608', 'FINATRUST MICROFINANCE BANK'), ('011', 'First Bank PLC'), ('214', 'First City Monument Bank'), ('058', 'Guaranty Trust Bank'), ('030', 'Heritage Bank'), ('090175', 'Highstreet Microfinance Bank'), ('301', 'Jaiz Bank'), ('082', 'Keystone Bank'), ('090267', 'Kudimoney MF Bank'), ('076', 'Polaris bank'), ('101', 'ProvidusBank PLC'), ('221', 'Stanbic IBTC Bank'), ('068', 'Standard Chaterted bank PLC'), ('232', 'Sterling Bank PLC'), ('100', 'Suntrust Bank'), ('032', 'Union Bank PLC'), ('033', 'United Bank for Africa'), ('215', 'Unity Bank PLC'), ('035', 'Wema Bank PLC'), ('057', 'Zenith bank PLC')], max_length=100, null=True, verbose_name='bank'),
        ),
        migrations.AlterField(
            model_name='flutterwavebankaccount',
            name='bank_country_code',
            field=models.CharField(blank=True, default='NG', max_length=2, null=True, verbose_name='bank country code'),
        ),
        migrations.AlterField(
            model_name='flutterwavepaymentprovider',
            name='prefix',
            field=models.CharField(default='goodup', max_length=100),
        ),
    ]
