# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0012_auto_20200812_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basestatistic',
            options={'ordering': ['sequence'], 'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterModelOptions(
            name='databasestatistic',
            options={'verbose_name': 'Engagement statistic', 'verbose_name_plural': 'Engagement statistics'},
        ),
        migrations.AlterModelOptions(
            name='databasestatistictranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Engagement statistic Translation'},
        ),
        migrations.AlterModelOptions(
            name='impactstatistic',
            options={'verbose_name': 'Impact statistic', 'verbose_name_plural': 'Impact statistics'},
        ),
        migrations.AlterModelOptions(
            name='manualstatistic',
            options={'verbose_name': 'Custom statistic', 'verbose_name_plural': 'Custom statistics'},
        ),
        migrations.AlterModelOptions(
            name='manualstatistictranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Custom statistic Translation'},
        ),
        migrations.AlterField(
            model_name='databasestatistic',
            name='query',
            field=models.CharField(choices=[('people_involved', 'People involved'), ('participants', 'Participants'), ('activities_succeeded', 'Activities succeeded'), ('assignments_succeeded', 'Tasks succeeded'), ('events_succeeded', 'Events succeeded'), ('fundings_succeeded', 'Funding activities succeeded'), ('assignment_members', 'Task applicants'), ('event_members', 'Event participants'), ('assignments_online', 'Tasks online'), ('events_online', 'Events online'), ('fundings_online', 'Funding activities online'), ('donations', 'Donations'), ('donated_total', 'Donated total'), ('pledged_total', 'Pledged total'), ('amount_matched', 'Amount matched'), ('activities_online', 'Activities Online'), ('time_spent', 'Time spent'), ('members', 'Number of members')], db_index=True, max_length=30, verbose_name='query'),
        ),
        migrations.AlterField(
            model_name='databasestatistictranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.DatabaseStatistic'),
        ),
        migrations.AlterField(
            model_name='manualstatistic',
            name='icon',
            field=models.CharField(blank=True, choices=[('people', 'People'), ('time', 'Time'), ('money', 'Money'), ('trees', 'Trees'), ('animals', 'Animals'), ('jobs', 'Jobs'), ('co2', 'C02'), ('water', 'Water'), ('plastic', 'plastic'), ('task', 'Task'), ('task-completed', 'Task completed'), ('event', 'Event'), ('event-completed', 'Event completed'), ('funding', 'Funding'), ('funding-completed', 'Funding completed')], max_length=20, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='manualstatistictranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='statistics.ManualStatistic'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='language',
            field=models.CharField(blank=True, choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], max_length=7, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='type',
            field=models.CharField(choices=[('manual', 'Manual'), ('donated_total', 'Donated total'), ('pledged_total', 'Pledged total'), ('tasks_realized', 'Tasks realized'), ('task_members', 'Taskmembers'), ('people_involved', 'People involved'), ('participants', 'Participants'), ('amount_matched', 'Amount Matched'), ('votes_cast', 'Number of votes cast'), ('members', 'Number of members')], db_index=True, default='manual', max_length=20, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='ImpactStatisticTranslation',
        ),
    ]
