# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_logger', '0002_delete_paymentlogentry'),
        ('payments', '0007_auto_20201002_1055'),
        ('payments_docdata', '0004_merge_20170124_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docdatapayment',
            name='payment_ptr',
        ),
        migrations.RemoveField(
            model_name='docdatatransaction',
            name='transaction_ptr',
        ),
        migrations.DeleteModel(
            name='DocdataDirectdebitPayment',
        ),
        migrations.DeleteModel(
            name='DocdataPayment',
        ),
        migrations.DeleteModel(
            name='DocdataTransaction',
        ),
    ]
