# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_delete_vote'),
        ('fundraisers', '0008_delete_fundraiser'),
        ('suggestions', '0005_delete_suggestion'),
        ('rewards', '0010_delete_reward'),
        ('donations', '0012_delete_donation'),
        ('payments_lipisha', '0003_auto_20201002_1055'),
        ('projects', '0094_merge_20191107_0943'),
    ]

    operations1 = [
        #migrations.RemoveField(
        #    model_name='customprojectfieldsettings',
        #    name='project_settings',
        #),
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='country',
        ),
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='payout_account',
        ),
        migrations.RemoveField(
            model_name='project',
            name='promoter',
        ),
        migrations.RemoveField(
            model_name='project',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='task_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='theme',
        ),
    ]

    operations = [
    ]
    foo = [
        migrations.RemoveField(
            model_name='projectaddon',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='projectaddon',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectbudgetline',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectcreatetemplate',
            name='project_settings',
        ),
        migrations.RemoveField(
            model_name='projectlocation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectphaselog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectphaselog',
            name='status',
        ),
        #migrations.RemoveField(
        #    model_name='projectsearchfilter',
        #    name='project_settings',
        #),
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='file',
            field=models.FileField(upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='name',
            field=models.CharField(blank=True, help_text='Defaults to filename, if left blank', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CustomProjectField',
        ),
        migrations.DeleteModel(
            name='CustomProjectFieldSettings',
        ),
        #migrations.DeleteModel(
        #    name='Project',
        #),
        migrations.DeleteModel(
            name='ProjectAddOn',
        ),
        migrations.DeleteModel(
            name='ProjectBudgetLine',
        ),
        migrations.DeleteModel(
            name='ProjectCreateTemplate',
        ),
        migrations.DeleteModel(
            name='ProjectLocation',
        ),
        migrations.DeleteModel(
            name='ProjectPhaseLog',
        ),
        #migrations.DeleteModel(
        #    name='ProjectPlatformSettings',
        #),
        migrations.DeleteModel(
            name='ProjectSearchFilter',
        ),
    ]
