# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_stripe', '0004_auto_20200318_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stripepayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='stripesourcepayment',
            options={'base_manager_name': 'objects'},
        ),
    ]
