# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('looker', '0003_init_looker_embeds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookerembed',
            name='type',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('look', 'Look'), ('space', 'Space')], max_length=10, verbose_name='type'),
        ),
    ]
