# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0016_auto_20200820_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impacttype',
            options={'ordering': ('id',), 'verbose_name': 'impact type', 'verbose_name_plural': 'impact types'},
        ),
        migrations.AlterField(
            model_name='impacttype',
            name='icon',
            field=models.CharField(blank=True, choices=[('people', 'People'), ('time', 'Time'), ('money', 'Money'), ('trees', 'Trees'), ('animals', 'Animals'), ('jobs', 'Jobs'), ('co2', 'C02'), ('water', 'Water'), ('plastic', 'plastic'), ('task', 'Task'), ('task-completed', 'Task completed'), ('event', 'Event'), ('event-completed', 'Event completed'), ('funding', 'Funding'), ('funding-completed', 'Funding completed')], max_length=20, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='impacttypetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='impact.ImpactType'),
        ),
    ]
