# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_auto_20191101_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
