# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_auto_20200915_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'permissions': (('api_read_skill', 'Can view skills through the API'),), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='skilltranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tasks.Skill'),
        ),
    ]
