# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-03 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_migrate_tasks_to_activities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'permissions': (('api_read_skill', 'Can view skills through the API'),), 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
