# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_telesom', '0004_auto_20200707_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telesompayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='telesompayment',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='telesompayment',
            name='response',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='telesompaymentprovider',
            name='api_url',
            field=models.CharField(default='https://sandbox.safarifoneict.com/asm/', max_length=100),
        ),
        migrations.AlterField(
            model_name='telesompaymentprovider',
            name='prefix',
            field=models.CharField(default='goodup', max_length=10),
        ),
    ]
