# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_delete_donation'),
        ('rewards', '0009_auto_20191104_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
