# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding_pledge', '0005_auto_20191111_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pledgepayment',
            options={'base_manager_name': 'objects'},
        ),
    ]
