# Generated by Django 3.0.8 on 2020-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactmessage_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in progress', 'In progress'), ('closed', 'Closed')], default='new', max_length=20, verbose_name='status'),
        ),
    ]
