# Generated by Django 3.0.8 on 2020-10-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20180424_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsadapter',
            name='type',
            field=models.CharField(default='GoogleAnalytics', max_length=100),
        ),
    ]
