# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bb_projects', '0015_auto_20190329_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectphasetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectphasetranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='projecttheme',
            options={'permissions': (('api_read_projecttheme', 'Can view theme through API'),), 'verbose_name': 'theme', 'verbose_name_plural': 'themes'},
        ),
        migrations.AlterModelOptions(
            name='projectthemetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'theme Translation'},
        ),
        migrations.AlterField(
            model_name='projectthemetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='bb_projects.ProjectTheme'),
        ),
    ]
