# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_auto_20201002_1055'),
        ('bb_projects', '0016_auto_20201002_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectPhase',
        ),
        migrations.DeleteModel(
            name='ProjectPhaseTranslation',
        ),
    ]
