# Generated by Django 3.0.8 on 2020-10-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb_accounts', '0003_useraddress_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
