# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20161004_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
