# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding_lipisha', '0008_lipishabankaccount_mpesa_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lipishapayment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterField(
            model_name='lipishabankaccount',
            name='mpesa_code',
            field=models.CharField(blank=True, help_text='Create a channel here: https://app.lypa.io/account and copy the generated `Number`.', max_length=50, null=True, unique=True, verbose_name='MPESA code'),
        ),
        migrations.AlterField(
            model_name='lipishabankaccount',
            name='swift',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SWIFT/Routing Code'),
        ),
        migrations.AlterField(
            model_name='lipishapayment',
            name='method',
            field=models.CharField(default='Paybill (M-Pesa)', max_length=30),
        ),
        migrations.AlterField(
            model_name='lipishapaymentprovider',
            name='paybill',
            field=models.CharField(help_text='Find this at https://app.lypa.io/payment under `Business Number`', max_length=10, verbose_name='Business Number'),
        ),
        migrations.AlterField(
            model_name='lipishapaymentprovider',
            name='prefix',
            field=models.CharField(default='goodup', max_length=100),
        ),
    ]
