# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_user'),
        ('payments', '0007_auto_20201002_1055'),
        ('payments_voucher', '0002_auto_20201002_1055'),
        ('donations', '0012_delete_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
