# Generated by Django 3.0.8 on 2020-10-02 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0004_merge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
