# Generated by Django 3.0.8 on 2020-10-02 08:52

import bluebottle.files.validators
import bluebottle.utils.fields
import bluebottle.utils.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0012_category_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='Category image', max_length=255, null=True, upload_to='categories/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image_logo',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='Category Logo image', max_length=255, null=True, upload_to='categories/logos/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='video',
            field=models.FileField(blank=True, help_text='This video will autoplay at the background. Allowed types are mp4, ogg, 3gp, avi, mov and webm. File should be smaller then 10MB.', max_length=255, null=True, upload_to='banner_slides/', validators=[bluebottle.files.validators.validate_video_file_size, bluebottle.utils.validators.FileMimetypeValidator(['video/ogg', 'video/mp4', 'video/webm', 'video/3gpp', 'video/x-msvideo', 'video/quicktime'], None, 'invalid_mimetype')], verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='categorycontent',
            name='image',
            field=bluebottle.utils.fields.ImageField(blank=True, help_text='Accepted file format: .jpg, .jpeg & .png', max_length=255, null=True, upload_to='categories/content/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='categorycontent',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Setting a video url will replace the image. Only YouTube or Vimeo videos are accepted. Max: 100 characters.', max_length=100),
        ),
        migrations.AlterField(
            model_name='categorycontenttranslation',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Max: 190 characters.', max_length=190, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='categorycontenttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.CategoryContent'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='categories.Category'),
        ),
    ]
