# Generated by Django 3.0.8 on 2020-10-02 08:52

import bluebottle.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentplugins', '0005_auto_20170818_1441'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pictureitem',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='pictureitem',
            name='align',
            field=models.CharField(choices=[('float-left', 'Float left'), ('center', 'Center'), ('float-right', 'Float right')], max_length=50, verbose_name='Align'),
        ),
        migrations.AlterField(
            model_name='pictureitem',
            name='image',
            field=bluebottle.utils.fields.ImageField(upload_to='content_images', verbose_name='Picture'),
        ),
    ]
